service: httpApi

configValidationMode: error

plugins:
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: nodejs16.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - httpApi:
          method: get
          path: /hello
    handler: src/handler.hello
