service: ts-node-example

configValidationMode: error
deprecationNotificationMode: error

plugins:
  - serverless-offline

provider:
  memorySize: 1024
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - http:
          method: get
          path: hello
    handler: src/bridge.hello
