service: serverless-plugin-typescript-example

configValidationMode: error
deprecationNotificationMode: error

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  architecture: arm64
  deploymentMethod: direct
  memorySize: 1024
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - http:
          method: get
          path: hello
    handler: src/index.hello
