service: lambda-invoke

plugins:
  - serverless-offline

provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Resource: '*'
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - http:
          method: get
          path: test-handler
    handler: handler.hello

  toBeInvoked:
    handler: handler.toBeInvoked
