service: schedule

plugins:
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

functions:
  schedule1:
    events:
      - schedule: rate(1 minute)
    handler: handler.schedule1

  schedule2:
    events:
      - schedule:
          enabled: true
          input:
            foo1: bar1
            foo2: bar2
            foobar:
              test: 1
          rate: rate(2 minutes)
    handler: handler.schedule2
