service: serverless-webpack-example

configValidationMode: error
deprecationNotificationMode: error

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  architecture: arm64
  deploymentMethod: direct
  memorySize: 1024
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - http:
          method: get
          path: hello
    handler: src/handler.hello
