service: websocket

configValidationMode: error
deprecationNotificationMode: error

plugins:
  - serverless-offline

provider:
  deploymentMethod: direct
  memorySize: 1024
  name: aws
  region: us-east-1 # default
  runtime: nodejs16.x
  stage: dev
  versionFunctions: false

functions:
  connect:
    events:
      - websocket:
          route: $connect
    handler: src/handler.connect

  disconnect:
    events:
      - websocket:
          route: $disconnect
    handler: src/handler.disconnect

  default:
    events:
      - websocket:
          route: $default
    handler: src/handler._default
