service: websocket

configValidationMode: error
deprecationNotificationMode: error

plugins:
  - serverless-offline

provider:
  architecture: arm64
  deploymentMethod: direct
  memorySize: 1024
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: dev
  versionFunctions: false

functions:
  initiateOneWay:
    events:
      - http:
          method: post
          path: initiate-one-way
    handler: src/handler.initiateOneWay

  connect:
    events:
      - websocket:
          route: $connect
    handler: src/handler.connect

  disconnect:
    events:
      - websocket:
          route: $disconnect
    handler: src/handler.disconnect

  default:
    events:
      - websocket:
          route: $default
          routeResponseSelectionExpression: $default
    handler: src/handler.defaultRoute
