service: usage-with-nodemon

plugins:
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: nodejs10.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    events:
      - http:
          method: get
          path: hello
    handler: src/handler.hello
